language: php
dist: xenial
services:
    - mysql
cache:
    directories:
        - $HOME/.composer/cache/files
addons:
    postgresql: 9.6
    apt:
        packages:
            - postgresql-9.6-postgis-2.3
env:
    global:
        - COMPOSER_ROOT_VERSION=4.x-dev
matrix:
    include:
        -
            php: 7.1
            env: 'DB=PGSQL RECIPE_VERSION=4.3.x-dev  PHPUNIT_TEST=1'
        -
            php: 7.2
            env: 'DB=MYSQL RECIPE_VERSION=4.4.x-dev PHPUNIT_TEST=1'
        -
            php: 7.3
            env: 'DB=MYSQL RECIPE_VERSION=4.4.x-dev PHPUNIT_COVERAGE_TEST=1'
        -
            php: 7.3
            env: 'DB=MYSQL RECIPE_VERSION=4.4.x-dev PHPUNIT_TEST=1'
        -
            php: 7.3
            env: 'DB=MYSQL RECIPE_VERSION=4.x-dev PHPUNIT_TEST=1'
        -
            php: 7.3
            env: 'DB=MYSQL RECIPE_VERSION=4.x-dev PHPCS_TEST=1'
        -
            php: 7.4
            env: PHPCS_TEST=1
        -
            php: 7.4
            env: DUPLICATE_CODE_CHECK=1
        -
            php: 7.4
            env: LINT_CHECK=1
        -
            php: 7.4
            env: PHPSTAN_TEST=1
before_script:
    - 'psql -c ''create database travis_ci_test;'' -U postgres'
    - 'phpenv rehash'
    - 'phpenv config-rm xdebug.ini'
    - 'echo ''memory_limit = 2G'' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini'
    - 'composer validate'
    - 'composer require silverstripe/recipe-cms:"$RECIPE_VERSION" silverstripe/recipe-testing:^1 --no-update'
    - 'composer require --no-update silverstripe/widgets'
    - 'if [[ $BEHAT_TEST ]]; then composer require --no-update silverstripe/behat-extension:4.x-dev; fi;'
    - 'if [[ $DB == PGSQL ]]; then composer require silverstripe/postgresql:^2 --no-update; fi'
    - 'composer install --prefer-source --no-interaction --no-progress --no-suggest --optimize-autoloader --verbose --profile'
    - 'vendor/bin/sake dev/build flush=all'
    - 'php vendor/silverstripe/framework/tests/dump_constants.php'
    - 'if [[ $DUPLICATE_CODE_CHECK ]]; then sudo apt remove -y nodejs && curl -sL https://deb.nodesource.com/setup_14.x -o nodesource_setup.sh && sudo bash nodesource_setup.sh && sudo apt install -y build-essential nodejs && which npm && npm install jscpd@3.2.1  ;fi'
script:
    - 'if [[ $PHPUNIT_TEST ]]; then vendor/bin/phpunit -d memory_limit=4G  tests/ '''' flush=1; fi'
    - 'if [[ $PHPUNIT_COVERAGE_TEST ]]; then phpdbg -qrr vendor/bin/phpunit -d memory_limit=4G --coverage-clover=coverage.xml   tests/ '''' flush=1  ; fi'
    - 'if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --config-set ignore_errors_on_exit 1 && vendor/bin/phpcs --config-set ignore_warnings_on_exit 1 && vendor/bin/phpcs src/ tests/ ; fi'
    - 'if [[ $NPM_TEST ]]; then git diff-files --quiet -w --relative=client; fi'
    - 'if [[ $NPM_TEST ]]; then git diff --name-status --relative=client; fi'
    - 'if [[ $NPM_TEST ]]; then yarn run test; fi'
    - 'if [[ $NPM_TEST ]]; then yarn run lint; fi'
    - 'if [[ $BEHAT_TEST ]]; then vendor/bin/behat @silverstripe-elemental; fi'
    - null
    - 'if [[ $PHPCS_TEST ]]; then vendor/bin/phpcs --standard=ruleset.xml --extensions=php --tab-width=4 -sp src tests ; fi'
    - 'if [[ $DUPLICATE_CODE_CHECK ]]; then node_modules/jscpd/bin/jscpd src && node_modules/jscpd/bin/jscpd tests ; fi'
    - 'if [[ $LINT_CHECK ]]; then vendor/bin/parallel-lint src/ tests/ ; fi'
    - 'if [[ $PHPSTAN_TEST ]]; then vendor/bin/phpstan analyse --level=6 -c tests/phpstan.neon src/ ; fi'
after_success:
    - 'if [[ $PHPUNIT_COVERAGE_TEST ]]; then bash <(curl -s https://codecov.io/bash) -f coverage.xml; fi'
